### ISSUE TITLE
Configurable output location

### ISSUE THREAD

**Issue by MengXiangxi** [YixinChen-AI/LUCID#1]
Please let the users specify the directory and file name of the output label nifti file, so as to provide even more flexibility.

Thank you!

**Comment by MengXiangxi** [comment]
![f93083e064018ad5a3fa0e0f30c8686](https://github.com/YixinChen-AI/LUCID/assets/10251566/72e0614c-2cb5-4634-ab80-4ce76485c264)

Related: also put the converted `%FILENAME%_lucid.nii.gz` to the `./lucid` directory.

**Comment by YixinChen-AI** [comment]
have added argu "outputpath". You could customize the output specific path. Usage could check Readme.
